#
# makefile for Magic documentation
#

CADDIR = /udir/mayo/cadhome

install:
	-mkdir ${CADDIR}/lib/magic/tutorial
	-rm -f ${CADDIR}/lib/magic/tutorial/*
	cp *.cmd *.mag *.net ${CADDIR}/lib/magic/tutorial
