#!/bin/csh -f
#
# :makeforce name modules
#
# rcsid $Header: :makeforce,v 1.1 89/04/03 16:15:30 mayo Exp $
#

set name=$argv[1]
foreach mod ( $argv[2-] )
	echo ' '
	echo ------- Doing $mod -------
	echo -n "pushd "
	pushd $mod
	set nonomatch
	rm -f *.o
	unset nonomatch
	make $name
	echo -n "popd "
	popd
end
